openapi: 3.0.0
info:
  title: HeySpace
  version: '1.0'
  description: HeySpace API reference
  contact:
    email: g.pasieka@timecamp.com
    name: Grzegorz Pasieka
servers:
  - url: 'https://app.hey.space/api'
    description: HeySpace
paths:
  '/projects/{projectId}':
    parameters:
      - schema:
          type: string
        name: projectId
        in: path
        required: true
    get:
      summary: Get project
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/createprojectsuccessresponse.v1.yaml
      tags:
        - Project
      description: Get Project details
      operationId: get_project
    patch:
      summary: Update project
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/emptysuccessresponse.v1.yaml
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/project.v1.yaml
      operationId: update_project
      tags:
        - Project
components:
  schemas: {}
  securitySchemes: {}
