openapi: 3.0.0
info:
  title: HeySpace
  version: '1.0'
  description: ''
  contact:
    email: g.pasieka@timecamp.com
    name: Grzegorz Pasieka
servers:
  - url: 'https://app.hey.space/api'
    description: HeySpace
paths:
  '/projects/{projectId}':
    parameters:
      - type: string
        name: projectId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get project data
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: ./models/project.v1.yaml
              examples: {}
        '404':
          description: Not Found
      parameters: []
      requestBody: {}
      description: ''
components:
  schemas: {}
  securitySchemes: {}
